In [47]:
#Pandas 
import numpy as np
import pandas as pd
data=np.array([[15,125,45,85],[12,172,81,105],[29,161,59,115],[18,179,75,120]])
print(data.ndim)
print(type(data))

2
<class 'numpy.ndarray'>

In [48]:
df=pd.DataFrame(data)
df

    0    1   2    3
0  15  125  45   85
1  12  172  81  105
2  29  161  59  115
3  18  179  75  120

In [49]:
#giving columns name 
df.columns=["Age","Height","Weight","Bp"]
df

   Age  Height  Weight   Bp
0   15     125      45   85
1   12     172      81  105
2   29     161      59  115
3   18     179      75  120

In [50]:
#giving row names
df.index=["a","b","c","d"]
df

   Age  Height  Weight   Bp
a   15     125      45   85
b   12     172      81  105
c   29     161      59  115
d   18     179      75  120

In [51]:
#Calculations on particular column
print(df["Bp"].min())
print(df["Bp"].max())
print(df["Bp"].mean())
print(df["Bp"].median())
print(df["Bp"].mode())
print(df["Bp"].std())
print(df["Bp"].var())

85
120
106.25
110.0
0     85
1    105
2    115
3    120
Name: Bp, dtype: int64
15.478479684172259
239.58333333333334

In [52]:
#Describe fucntion gives  the statistical calculations
df.describe()

             Age      Height     Weight         Bp
count   4.000000    4.000000   4.000000    4.00000
mean   18.500000  159.250000  65.000000  106.25000
std     7.416198   24.005208  16.248077   15.47848
min    12.000000  125.000000  45.000000   85.00000
25%    14.250000  152.000000  55.500000  100.00000
50%    16.500000  166.500000  67.000000  110.00000
75%    20.750000  173.750000  76.500000  116.25000
max    29.000000  179.000000  81.000000  120.00000

In [57]:
#calling by column names
print(df)
print(df[["Age","Height"]])
print(df[["Age","Weight"]])

   Age  Height  Weight   Bp
a   15     125      45   85
b   12     172      81  105
c   29     161      59  115
d   18     179      75  120
   Age  Height
a   15     125
b   12     172
c   29     161
d   18     179
   Age  Weight
a   15      45
b   12      81
c   29      59
d   18      75

In [65]:
#two function for slicing
#iloc based on index values 
#loc  based on names

#iloc
print("--------iloc------")
print(df.iloc[0:2,1:3])
print(df.iloc[1:2,0:2])

print("------loc--------")
print(df.loc[['b','c'],["Age","Bp"]])
df.loc[['a','d'],["Height","Weight"]]

--------iloc------
   Height  Weight
a     125      45
b     172      81
   Age  Height
b   12     172
------loc--------
   Age   Bp
b   12  105
c   29  115

   Height  Weight
a     125      45
d     179      75

In [95]:
#Using Data set
df=pd.read_csv("nyc_weather_dataset.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [96]:
print(df.shape)  #Tell the count of rows and columns

(31, 11)

In [94]:
#prinitng only selected rows and columns
df.iloc[0:10,:]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109

In [88]:
df.iloc[0:5:2,::2] #using step value

,EST,DewPoint,Sea Level PressureIn,WindSpeedMPH,CloudCover,WindDirDegrees
0,01-01-2016,23,30.03,8,5,281
2,01-03-2016,21,29.86,8,1,277
4,01-05-2016,-3,30.57,5,0,333

In [91]:
df.iloc[0:7,0:5]

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn
0  01-01-2016           38        23        52                 30.03
1  01-02-2016           36        18        46                 30.02
2  01-03-2016           40        21        47                 29.86
3  01-04-2016           25         9        44                 30.05
4  01-05-2016           20        -3        41                 30.57
5  01-06-2016           33         4        35                 30.50
6  01-07-2016           39        11        33                 30.28

In [98]:
#Head funxtion
df.head()  #Gtive Top 5 rows

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333

In [100]:
df.head(7) #can also give the argument that how much of rows we need

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293

In [101]:
#Tail
df.tail() #Last 5 rows

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [102]:
df.tail(8) #give the rows from last count will be argument we give

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [105]:
#info fucntion will give the total information about the data set 
'''
type
rows count
column count
each column datatype
nonull values count
memory usage

'''
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EST                   31 non-null     object
 1   Temperature           31 non-null     int64
 2   DewPoint              31 non-null     int64
 3   Humidity              31 non-null     int64
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64
 6   WindSpeedMPH          31 non-null     int64
 7   PrecipitationIn       31 non-null     object
 8   CloudCover            31 non-null     int64
 9   Events                9 non-null      object
 10  WindDirDegrees        31 non-null     int64
dtypes: float64(1), int64(7), object(3)
memory usage: 2.8+ KB

In [107]:
#to find the null vlaue we use two fucntions
'''
1. isnull()  ---->>> give the ture/false table where true is null value)
2. isnull().sum()   ----> it calculate all the null values in each column

'''
df.isnull()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,True,False
11,False,False,False,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,True,False
29,False,False,False,False,False,False,False,False,False,True,False
30,False,False,False,False,False,False,False,False,False,True,False

In [108]:
#add all null values in each column 
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             0
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64