In [60]:
import numpy as np 
import pandas as pd
df1=pd.read_csv("first_file.csv")
df2=pd.read_csv("second_file.csv")
df3=pd.read_csv("third_file.csv")

In [61]:
df1

    id   age  height  weight
0  101  24.0     175      85
1  102  25.0     165      75
2  103  30.0     168      72
3  104   NaN     172      78
4  105  28.0     170      76

In [62]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   age     4 non-null      float64
 2   height  5 non-null      int64
 3   weight  5 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes

In [56]:
int(df1["weight"].mean())
df1.isnull().sum()

id        0
age       1
height    0
weight    0
dtype: int64

In [63]:
df1

    id   age  height  weight
0  101  24.0     175      85
1  102  25.0     165      75
2  103  30.0     168      72
3  104   NaN     172      78
4  105  28.0     170      76

In [64]:
#Replacing the Null value with the mean or median value
#Fillna method is used to replace the null vlaue
mean=int(df1["age"].mean())
df1["age"].fillna(value=mean,inplace=True)   #inplace is using because it affect the actual data if we wont use its not affect
df1

C:\Users\MIRZAS\AppData\Local\Temp\ipykernel_16400\3046281521.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["age"].fillna(value=mean,inplace=True)

    id   age  height  weight
0  101  24.0     175      85
1  102  25.0     165      75
2  103  30.0     168      72
3  104  26.0     172      78
4  105  28.0     170      76

In [65]:
df2

    id  age  height  weight
0  106   28     174      68
1  107   32     168      76
2  108   37     158      73
3  109   40     176      80
4  110   30     169      85

In [66]:
df3

  Gender   BP
0      M  120
1      F  140
2      M  145
3      F  132
4      M  130
5      F  150
6      M  147
7      F  132
8      F  128
9      F  130

In [69]:
#Concatination of two files  (Rows are adding the axis is default 0)
df4=pd.concat([df1,df2],ignore_index=True)
df4

    id   age  height  weight
0  101  24.0     175      85
1  102  25.0     165      75
2  103  30.0     168      72
3  104  26.0     172      78
4  105  28.0     170      76
5  106  28.0     174      68
6  107  32.0     168      76
7  108  37.0     158      73
8  109  40.0     176      80
9  110  30.0     169      85

In [73]:
#Concatination of two files columns (axis should be change to 1)
df5=pd.concat([df4,df3] , axis=1)
df5

    id   age  height  weight Gender   BP
0  101  24.0     175      85      M  120
1  102  25.0     165      75      F  140
2  103  30.0     168      72      M  145
3  104  26.0     172      78      F  132
4  105  28.0     170      76      M  130
5  106  28.0     174      68      F  150
6  107  32.0     168      76      M  147
7  108  37.0     158      73      F  132
8  109  40.0     176      80      F  128
9  110  30.0     169      85      F  130

In [81]:
print("------------average age of male and female-------------------- ")
df5.groupby("Gender")["age"].mean()

------------average age of male and female--------------------

Gender
F    31.0
M    28.5
Name: age, dtype: float64

In [82]:
print("----------average height of male and female ------------")
df5.groupby("Gender")["height"].mean()

----------average height of male and female ------------

Gender
F    169.00
M    170.25
Name: height, dtype: float64

In [83]:
print("---------average weight of male and female -----------------")
df5.groupby("Gender")["weight"].mean()

---------average weight of male and female -----------------

Gender
F    76.50
M    77.25
Name: weight, dtype: float64

In [84]:
df5

    id   age  height  weight Gender   BP
0  101  24.0     175      85      M  120
1  102  25.0     165      75      F  140
2  103  30.0     168      72      M  145
3  104  26.0     172      78      F  132
4  105  28.0     170      76      M  130
5  106  28.0     174      68      F  150
6  107  32.0     168      76      M  147
7  108  37.0     158      73      F  132
8  109  40.0     176      80      F  128
9  110  30.0     169      85      F  130

In [91]:
#Drop method
# in this also rows is default axis =0 
# column to be changed to axis =1
df5
df5.drop("BP",axis=1)

    id   age  height  weight Gender
0  101  24.0     175      85      M
1  102  25.0     165      75      F
2  103  30.0     168      72      M
3  104  26.0     172      78      F
4  105  28.0     170      76      M
5  106  28.0     174      68      F
6  107  32.0     168      76      M
7  108  37.0     158      73      F
8  109  40.0     176      80      F
9  110  30.0     169      85      F